all:	union bufferOverflow cwe120 unsafe globalvars cwe190 cwe134

union:
	gcc -o union.o union.c 
bufferOverflow:
	gcc -o bufferOverflow.o bufferOverflow.c
cwe120:
	gcc -o cwe-120.o cwe-120.c
unsafe:
	gcc -o unsafestrcat.o unsafestrcat.c 
globalvars:
	gcc -o globalvars.o globalvars.c
cwe190:
	gcc -o cwe-190.o cwe-190.c
cwe134:
	gcc -o cwe-134.o cwe-134.c
lopp:
	gcc -o infiniteloop.o infiniteloop.c
