all:	union bufferOverflow cwe120 unsafe globalvars cwe190 cwe134 

union:
	gcc c-test-proj/union.c 
bufferOverflow:
	gcc c-test-proj/bufferOverflow.c
cwe120:
	gcc  c-test-proj/cwe-120.c
unsafe:
	gcc  c-test-proj/unsafestrcat.c 
globalvars:
	gcc  c-test-proj/globalvars.c
cwe190:
	gcc  c-test-proj/cwe-190.c
cwe134:
	gcc  c-test-proj/cwe-134.c
